version: '3'
services:
  django:
    build:
      context: django
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ./django:/django
  builder:
    build:
      context: qa_tools
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
      - ./qa_tools:/app
    command: sleep infinity
