version: '3'
services:
  django:
    build:
      context: django
      dockerfile: Dockerfile
    env_file: "django.env"
    environment:
      - ENV=${ENV}
      - http_proxy_url=${http_proxy_url}
    volumes:
      - .:/workspace:cached
      - ./django:/django
      - media:/data/media
    links:
      - redis
    depends_on:
      - celery
      - redis
      - websocketserver

  celery:
    build:
      context: django
      dockerfile: Dockerfile
    env_file: "django.env"
    environment:
      - ENV=${ENV}
      - http_proxy_url=${http_proxy_url}
    volumes:
      - ./django:/django
      - media:/data/media
      - artifacts:/data/artifacts
    links:
      - redis
    depends_on:
      - redis
      - websocketserver
    entrypoint: /home/user/venv/bin/celery -A mysite worker -l INFO

  websocketserver:
    build:
      context: django
      dockerfile: Dockerfile
    volumes:
      - ./django:/django
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "9000:9000"
    entrypoint: /home/user/venv/bin/python -u websocket_server.py --redis-host redis

  redis:
    image: redis

  builder:
    build:
      context: react_builder
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
      - ./react_builder:/app
    command: /home/node/venv/bin/fastapi dev --host 0.0.0.0 --port 8888 app
  
  nextjs:
    build:
      context: nextjs_app
      dockerfile: Dockerfile
    volumes:
      - ./nextjs_app:/home/node/nextjs_app
    ports:
      - "3000:3000"
    command: "./run_prod.sh"

  nginx:
    image: nginx
    depends_on:
      - django
      - nextjs
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/templates
      - media:/data/media
      - artifacts:/data/artifacts
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      NGINX_HOST: localhost
      NGINX_PORT: 80
      NGINX_APP_SERVER_NAME: django
      NGINX_APP_SERVER_PORT: 8000
      NGINX_NEXTJS_SERVER_NAME: nextjs
      NGINX_NEXTJS_SERVER_PORT: 3000


volumes:
  media:
  artifacts:
