# Generated by Django 5.1.2 on 2024-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
