# Generated by Django 5.1.2 on 2024-10-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('system_message', models.TextField(blank=True, null=True)),
                ('autorun', models.BooleanField(default=False)),
                ('max_iterations', models.IntegerField(default=1)),
                ('build_servers', models.ManyToManyField(blank=True, related_name='build_configs', to='assistant.server')),
                ('interaction_servers', models.ManyToManyField(blank=True, related_name='interaction_configs', to='assistant.server')),
                ('lint_servers', models.ManyToManyField(blank=True, related_name='lint_configs', to='assistant.server')),
                ('llm_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to='assistant.server')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.preset')),
                ('test_servers', models.ManyToManyField(blank=True, related_name='test_configs', to='assistant.server')),
            ],
        ),
    ]
