# Generated by Django 5.1.2 on 2024-10-25 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_tree', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='assistant.revision')),
            ],
        ),
    ]
