# Generated by Django 5.1.2 on 2024-10-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_build_lintercheck_testrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='operation_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='assistant.operationsuite'),
        ),
        migrations.AddField(
            model_name='lintercheck',
            name='operation_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lints', to='assistant.operationsuite'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='operation_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='assistant.operationsuite'),
        ),
    ]
