# Generated by Django 5.1.2 on 2024-10-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_comment_thread_comment_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='head',
        ),
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assistant.thread'),
        ),
    ]
