# Generated by Django 5.1.2 on 2024-10-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_remove_thread_head_alter_comment_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('code', 'Code'), ('mixture', 'Mixture')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.JSONField(blank=True, null=True)),
                ('mixed_modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mixture', to='assistant.modality')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User'), ('system', 'System')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_message', to='assistant.revision')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chat')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_message', to='assistant.modality')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='assistant.multimediamessage')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assistant.multimediamessage'),
            preserve_default=False,
        ),
    ]
