# Generated by Django 5.1.2 on 2024-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_chat_modality_multimediamessage_revision_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
