# Generated by Django 5.1.2 on 2024-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_modality_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
