# Generated by Django 5.1.2 on 2024-11-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_alter_modality_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modality',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='GenerationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('response_metadata', models.JSONField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='assistant.server')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('finished', models.BooleanField(default=False)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='assistant.chat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='assistant.multimediamessage')),
                ('generation_metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation', to='assistant.generationmetadata')),
            ],
        ),
    ]
