# Generated by Django 5.1.3 on 2024-12-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_alter_modality_options_generationmetadata_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediamessage',
            name='child_index',
            field=models.IntegerField(default=0),
        ),
    ]
