# Generated by Django 5.1.3 on 2024-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_multimediamessage_child_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
