# Generated by Django 5.1.3 on 2024-12-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='generation_type',
            field=models.CharField(choices=[('message', 'Message'), ('chat_title', 'Chat title'), ('chat_picture', 'Chat picture')], default='message', max_length=20),
        ),
    ]
