# Generated by Django 5.1.4 on 2024-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_revision_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='llm_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
