# Generated by Django 5.1.5 on 2025-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0019_generationmetadata_system_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediamessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/audio'),
        ),
    ]
