# Generated by Django 5.1.5 on 2025-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0020_multimediamessage_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('audio', models.FileField(upload_to='audio_samples')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='multimediamessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_samples'),
        ),
    ]
