# Generated by Django 5.1.5 on 2025-04-30 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_speechsample_alter_multimediamessage_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_path', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='resources')),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='assistant.chat')),
            ],
        ),
    ]
