# Generated by Django 5.1.5 on 2025-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0023_alter_resource_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='zipfile',
            field=models.FileField(blank=True, null=True, upload_to='resources/zipfiles'),
        ),
    ]
