# Generated by Django 5.1.5 on 2025-08-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0025_chat_coding_mode_configuration_coder_system_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediamessage',
            name='thoughts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
