# Generated by Django 5.2.10 on 2026-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0026_multimediamessage_thoughts'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='oai_item',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modality',
            name='modality_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('code', 'Code'), ('oai_item', 'Open AI Response Item'), ('mixture', 'Mixture')], max_length=10),
        ),
    ]
